//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcControlsToolkit.Core.DataAnnotations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcControlsToolkit.Core.DataAnnotations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DynamicRangeAttribute has been applied to an unsopported type.
        /// </summary>
        internal static string InvalidDynamicRangeApplication {
            get {
                return ResourceManager.GetString("InvalidDynamicRangeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Limits of DynamicRangeAttribute have invalid format.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested properties are not allowed as aggregation results: {0}.
        /// </summary>
        internal static string NestedPropertyNotAllowed {
            get {
                return ResourceManager.GetString("NestedPropertyNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumerable of type {0} has neither () not (int) constructor.
        /// </summary>
        internal static string NoConstructor {
            get {
                return ResourceManager.GetString("NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} public property found.
        /// </summary>
        internal static string NoPublicProperty {
            get {
                return ResourceManager.GetString("NoPublicProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumerables are non supported by {0}.
        /// </summary>
        internal static string NotSupportedEnumerables {
            get {
                return ResourceManager.GetString("NotSupportedEnumerables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interfaces are not supported by {0}.
        /// </summary>
        internal static string NotSupportedInterface {
            get {
                return ResourceManager.GetString("NotSupportedInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0} is not supported.
        /// </summary>
        internal static string NotSupportedOperation {
            get {
                return ResourceManager.GetString("NotSupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0} is not supported on {1}.
        /// </summary>
        internal static string NotSupportedOperationOn {
            get {
                return ResourceManager.GetString("NotSupportedOperationOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is not allowed in queries.
        /// </summary>
        internal static string PropertyNotAllowed {
            get {
                return ResourceManager.GetString("PropertyNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type {0} has no property named {1}.
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not in the required range.
        /// </summary>
        internal static string RangeStandardError {
            get {
                return ResourceManager.GetString("RangeStandardError", resourceCulture);
            }
        }
    }
}
